Add infinite scroll component, "scroll to top button" and base pokemon page.
NikolasGumenyuk/pokedex pull request #8
Opened 2023-04-02 18:03 UTC by NikolasGumenyuk

2023-04-03 09:53 UTC, LobodaAndreyEK requested changes

2023-04-03 09:53 UTC, LobodaAndreyEK commented on src/components/PokemonCard/PokemonCard.tsx
> +    navigate(PathName.pokemon);
Please rewrite it with useParams

2023-04-03 09:53 UTC, LobodaAndreyEK commented on src/components/PokemonCard/PokemonCard.tsx
> +      onClick={() => navigateToPokemon()}
simplify

2023-04-03 09:53 UTC, LobodaAndreyEK commented on src/components/PokemonsList/PokemonsList.tsx
> +    });
When you add some listener, you have to remove it on component unmount

2023-05-13 16:18 UTC, NataliaHanzhuha approved these changes
fixed bugs

2023-05-13 16:22 UTC, closed without merging